### PR TITLE
add github action for lint and test

### PR DESCRIPTION
**Pull request by lambley**
- add workflow to run lint and test, and exit if either fail
- add sonarless-scan - only check for vulnerabilities, code smells, duplications and coverage

### CODE REVIEW

**Comment by lambley** [comment]
I'll add pushing to Azure Container registry to the CI actions

**Comment by WeaponOfChoice-Solirius** [comment]
As mentioned in our standup - please Dockerise the app, and include that in your CI workflow

**Review by WeaponOfChoice-Solirius — CHANGES_REQUESTED** [review]
Dockerfile and build to ECR or similar
Add image build and deploy to ECS or similar

**Comment by lambley** [comment]
> Dockerfile and build to ECR or similar Add image build and deploy to ECS or similar

@WeaponOfChoice-Solirius I've added a CD workflow for tagging and pushing the images to my Azure Container Registry `filevault`

**Review by WeaponOfChoice-Solirius — APPROVED** [review]
Looks great! Next steps would be to actually use the built image, in a hosting service. But this PR looks ready.

Just make sure with any image, test it locally, make sure you can access the app, and that it works

**Pull request merged**
